### ISSUE TITLE
Setting EPICS_CA_MAX_ARRAY_BYTES incorrectly

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/machine-applications#147]
@fernandohds564 , I think setting this env variable should occur before importing pcaspy (and thus loading CA libraries)

https://github.com/lnls-sirius/machine-applications/blob/a6c854a715ee33ba77a8829120c18beea1eeee97/li-ap-energy/scripts/sirius-ioc-li-ap-energy.py#L9

**Comment by fernandohds564** [comment]
@xresende, I don't think it is necessary, because I think this variable is consulted when the IOC is initialized.
